# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogOptions.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(815, 535)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(815, 535))
        Dialog.setMaximumSize(QtCore.QSize(820, 535))
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 801, 521))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listWidgetOptions = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.listWidgetOptions.setObjectName("listWidgetOptions")
        self.horizontalLayout.addWidget(self.listWidgetOptions)
        self.verticalWidget = QtWidgets.QWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalWidget.sizePolicy().hasHeightForWidth())
        self.verticalWidget.setSizePolicy(sizePolicy)
        self.verticalWidget.setMaximumSize(QtCore.QSize(200, 180))
        self.verticalWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalWidget.setAutoFillBackground(False)
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayoutInput = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayoutInput.setObjectName("verticalLayoutInput")
        self.labelInputValue2 = QtWidgets.QLabel(self.verticalWidget)
        self.labelInputValue2.setMaximumSize(QtCore.QSize(100, 20))
        self.labelInputValue2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelInputValue2.setWordWrap(False)
        self.labelInputValue2.setObjectName("labelInputValue2")
        self.verticalLayoutInput.addWidget(self.labelInputValue2)
        self.textEditInputValue2 = QtWidgets.QTextEdit(self.verticalWidget)
        self.textEditInputValue2.setMaximumSize(QtCore.QSize(100, 30))
        self.textEditInputValue2.setObjectName("textEditInputValue2")
        self.verticalLayoutInput.addWidget(self.textEditInputValue2)
        self.labelInputValue1 = QtWidgets.QLabel(self.verticalWidget)
        self.labelInputValue1.setMaximumSize(QtCore.QSize(100, 20))
        self.labelInputValue1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelInputValue1.setWordWrap(False)
        self.labelInputValue1.setObjectName("labelInputValue1")
        self.verticalLayoutInput.addWidget(self.labelInputValue1)
        self.textEditInputValue1 = QtWidgets.QTextEdit(self.verticalWidget)
        self.textEditInputValue1.setMaximumSize(QtCore.QSize(100, 30))
        self.textEditInputValue1.setObjectName("textEditInputValue1")
        self.verticalLayoutInput.addWidget(self.textEditInputValue1)
        self.horizontalLayout.addWidget(self.verticalWidget, 0, QtCore.Qt.AlignHCenter)
        self.scrollAreaDescription = QtWidgets.QScrollArea(self.verticalLayoutWidget)
        self.scrollAreaDescription.setAccessibleName("")
        self.scrollAreaDescription.setAutoFillBackground(True)
        self.scrollAreaDescription.setWidgetResizable(True)
        self.scrollAreaDescription.setObjectName("scrollAreaDescription")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 328, 480))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setGeometry(QtCore.QRect(9, 9, 311, 471))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.labelOriginalImage = QtWidgets.QLabel(self.groupBox)
        self.labelOriginalImage.setGeometry(QtCore.QRect(0, 77, 309, 166))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelOriginalImage.sizePolicy().hasHeightForWidth())
        self.labelOriginalImage.setSizePolicy(sizePolicy)
        self.labelOriginalImage.setMinimumSize(QtCore.QSize(289, 150))
        self.labelOriginalImage.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelOriginalImage.setText("")
        self.labelOriginalImage.setPixmap(QtGui.QPixmap("../imgs/wallBlue.png"))
        self.labelOriginalImage.setAlignment(QtCore.Qt.AlignCenter)
        self.labelOriginalImage.setObjectName("labelOriginalImage")
        self.labelDescription = QtWidgets.QLabel(self.groupBox)
        self.labelDescription.setGeometry(QtCore.QRect(0, 31, 298, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDescription.sizePolicy().hasHeightForWidth())
        self.labelDescription.setSizePolicy(sizePolicy)
        self.labelDescription.setMinimumSize(QtCore.QSize(298, 0))
        self.labelDescription.setMaximumSize(QtCore.QSize(298, 16777215))
        self.labelDescription.setWordWrap(True)
        self.labelDescription.setObjectName("labelDescription")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(0, 54, 309, 16))
        self.label.setObjectName("label")
        self.labelDescriptionTitle = QtWidgets.QLabel(self.groupBox)
        self.labelDescriptionTitle.setGeometry(QtCore.QRect(0, 8, 309, 16))
        self.labelDescriptionTitle.setMaximumSize(QtCore.QSize(16777215, 20))
        self.labelDescriptionTitle.setObjectName("labelDescriptionTitle")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(0, 257, 309, 16))
        self.label_2.setObjectName("label_2")
        self.labelModifiedImage = QtWidgets.QLabel(self.groupBox)
        self.labelModifiedImage.setGeometry(QtCore.QRect(0, 280, 309, 167))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelModifiedImage.sizePolicy().hasHeightForWidth())
        self.labelModifiedImage.setSizePolicy(sizePolicy)
        self.labelModifiedImage.setMinimumSize(QtCore.QSize(289, 150))
        self.labelModifiedImage.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelModifiedImage.setText("")
        self.labelModifiedImage.setPixmap(QtGui.QPixmap("../imgs/wallBlue.png"))
        self.labelModifiedImage.setAlignment(QtCore.Qt.AlignCenter)
        self.labelModifiedImage.setObjectName("labelModifiedImage")
        self.scrollAreaDescription.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollAreaDescription)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
        self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelInputValue2.setText(_translate("Dialog", "InputValue"))
        self.labelInputValue1.setText(_translate("Dialog", "InputValue"))
        self.labelDescription.setText(_translate("Dialog", "Description"))
        self.label.setText(_translate("Dialog", "Imagem Original:"))
        self.labelDescriptionTitle.setText(_translate("Dialog", "Title"))
        self.label_2.setText(_translate("Dialog", "Imagem com Efeito aplicado:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
